import type { Metadata } from 'next'
import { SITE_URL } from '@/lib/site'
import type { Locale } from '@/types'

// Keywords optimized for recruiter + developer searches in each language.
// Mirrors the stack advertised on the stack screen (src/lib/tech-data.ts).
const KEYWORDS_EN = [
  'Tiago Estetele',
  'Web Developer',
  'Front-End Developer',
  'React Developer',
  'Next.js Developer',
  'TypeScript Developer',
  'JavaScript Developer',
  'WordPress Developer',
  'Frontend Engineer',
  'Full Stack Developer',
  'Strapi Developer',
  'AEM Developer',
  'Adobe Experience Manager',
  'Contentful',
  'Payload CMS',
  'Nest.js',
  'Node.js',
  'Gatsby',
  'Tailwind CSS',
  'SASS',
  'styled-components',
  'shadcn/ui',
  'MongoDB',
  'PostgreSQL',
  'Docker',
  'AI Engineering',
  'Prompt Engineering',
  'LangChain',
  'RAG',
  'Model Context Protocol',
  'Software Engineer',
  'Portfolio',
  'Brazil',
  'Remote Developer',
  'Brivia',
]

const KEYWORDS_PT = [
  'Tiago Estetele',
  'Desenvolvedor Web',
  'Desenvolvedor Front-End',
  'Desenvolvedor React',
  'Desenvolvedor Next.js',
  'TypeScript',
  'JavaScript',
  'Desenvolvedor Full Stack',
  'Engenheiro Front-End',
  'Portfolio',
  'Brasil',
  'Desenvolvedor Remoto',
  'WordPress',
  'Strapi',
  'AEM',
  'Adobe Experience Manager',
  'Contentful',
  'Payload CMS',
  'Nest.js',
  'Node.js',
  'Gatsby',
  'Tailwind CSS',
  'SASS',
  'styled-components',
  'shadcn/ui',
  'MongoDB',
  'PostgreSQL',
  'Docker',
  'Engenharia de IA',
  'Engenharia de Prompt',
  'LangChain',
  'RAG',
  'Model Context Protocol',
  'Brivia',
]

/** `localePrefix: 'as-needed'` — English is served unprefixed, `pt` carries `/pt`. */
export function urlFor(locale: Locale, path: string): string {
  const suffix = path === '/' ? '' : path
  return locale === 'pt' ? `${SITE_URL}/pt${suffix}` : `${SITE_URL}${suffix}`
}

/**
 * The OG image is generated by `[locale]/opengraph-image.tsx`, which only produces a
 * route at each locale root — sub-routes reuse the same image.
 */
function ogImageFor(locale: Locale) {
  return locale === 'pt' ? `${SITE_URL}/pt/opengraph-image` : `${SITE_URL}/opengraph-image`
}

const OG_ALT: Record<Locale, string> = {
  en: 'Tiago Estetele, Web Developer specialized in front-end',
  pt: 'Tiago Estetele, Desenvolvedor Web especializado em front-end',
}

interface PageMetadataOptions {
  locale: Locale
  /** Locale-agnostic route, e.g. `/` or `/about`. */
  path: string
  /**
   * Screen title. A string is run through the `%s | Tiago Estetele` template from the
   * locale layout; omit it on the home screen, where `absoluteTitle` stands alone.
   */
  title?: string
  absoluteTitle?: string
  description: string
  siteName: string
  /** 404 and other non-canonical screens opt out of indexing and hreflang. */
  indexable?: boolean
}

/**
 * Next.js merges metadata shallowly — a page that declares `openGraph` replaces the
 * parent's entirely — so every route builds its full social + canonical block here
 * rather than inheriting a partial one from the layout.
 */
export function buildPageMetadata({
  locale,
  path,
  title,
  absoluteTitle,
  description,
  siteName,
  indexable = true,
}: PageMetadataOptions): Metadata {
  const canonical = urlFor(locale, path)
  const image = ogImageFor(locale)
  const resolvedTitle = absoluteTitle ?? title ?? siteName

  return {
    title: absoluteTitle ? { absolute: absoluteTitle } : title,
    description,
    keywords: locale === 'pt' ? KEYWORDS_PT : KEYWORDS_EN,

    alternates: indexable
      ? {
          canonical,
          languages: {
            en: urlFor('en', path),
            'pt-BR': urlFor('pt', path),
            'x-default': urlFor('en', path),
          },
        }
      : undefined,

    robots: indexable
      ? {
          index: true,
          follow: true,
          'max-snippet': -1,
          'max-image-preview': 'large',
          'max-video-preview': -1,
          googleBot: {
            index: true,
            follow: true,
            'max-snippet': -1,
            'max-image-preview': 'large',
            'max-video-preview': -1,
          },
        }
      : { index: false, follow: true },

    openGraph: {
      type: 'website',
      url: canonical,
      title: resolvedTitle,
      description,
      siteName,
      locale: locale === 'pt' ? 'pt_BR' : 'en_US',
      alternateLocale: locale === 'pt' ? ['en_US'] : ['pt_BR'],
      images: [{ url: image, width: 1200, height: 630, alt: OG_ALT[locale], type: 'image/png' }],
    },

    twitter: {
      card: 'summary_large_image',
      title: resolvedTitle,
      description,
      images: [{ url: image, width: 1200, height: 630, alt: OG_ALT[locale] }],
    },
  }
}
