import type { TechCategory } from '@/types'

export const TECH_CATEGORIES: TechCategory[] = [
  {
    id: 'frontend',
    iconName: 'LayoutTemplate',
    gridSpan: 2,
    accentVariant: 'violet',
    tagVariant: 'default',
    tags: [
      'React',
      'Next.js',
      'TypeScript',
      'JavaScript',
      'PHP',
      'HTML5',
      'CSS3',
      'Tailwind CSS',
      'Styled Components',
      'Framer Motion',
    ],
  },
  {
    id: 'backend',
    iconName: 'Server',
    accentVariant: 'tangerine',
    tagVariant: 'default',
    tags: ['Node.js', 'Express', 'REST APIs', 'GraphQL'],
  },
  {
    id: 'cms',
    iconName: 'Database',
    accentVariant: 'violet',
    tagVariant: 'default',
    tags: ['WordPress', 'Strapi', 'Contentful', 'AEM'],
  },
  {
    id: 'database',
    iconName: 'DatabaseZap',
    accentVariant: 'green',
    tagVariant: 'default',
    tags: ['MySQL', 'PostgreSQL', 'MongoDB'],
  },
  {
    id: 'devops',
    iconName: 'Terminal',
    accentVariant: 'yellow',
    tagVariant: 'default',
    tags: ['Git', 'Docker', 'Vercel', 'GitHub Actions', 'Vite', 'Linux'],
  },
  {
    id: 'ai',
    iconName: 'Bot',
    gridSpan: 2,
    accentVariant: 'violet',
    tagVariant: 'violet',
    tags: [
      'ChatGPT',
      'GitHub Copilot',
      'Cursor',
      'Claude',
      'Prompt Engineering',
      'OpenAI API',
      'LangChain',
      'RAG',
      'MCP',
      'AI-driven Development',
      'Agent Skills',
      'Automation',
    ],
  },
]
